""
			+ "SELECT "
			+ "			a.id, "
			+ "			a.cars_in_operation_id, "
			+ "			a.car_license_no, "
			+ "			a.user_full_name, "
			+ "			a.car_responsible_person, "
			+ "			a.car_type, "
			+ "			a.person_or_cargo, "
			+ "			a.required_destination_name, "
			+ "			a.car_passengers, "
			+ "			case when a.required_departure_date_time > 0 then To_char( to_timestamp(a.required_departure_date_time/1000), "
			+ "			                          'YYYY-MM-DD HH24:MI:SS:MS') "
			+ "	             else '0' "
			+ "			end as required_departure_date_time, "
			+ "         required_departure_date_time as  required_departure, "
			+ "			case when a.required_arrival_date_time > 0 then To_char( to_timestamp(a.required_arrival_date_time/1000), "
			+ "			                          'YYYY-MM-DD HH24:MI:SS:MS') "
			+ "	             else '0' "
			+ "			end as required_arrival_date_time, "
			+ "         required_arrival_date_time as  required_arrival, "
			+ "			case when a.real_driving_start_date_time > 0 then To_char( to_timestamp(a.real_driving_start_date_time/1000), "
			+ "			                          'YYYY-MM-DD HH24:MI:SS:MS') "
			+ "	             else '0' "
			+ "			end as real_driving_start_date_time, "
			+ "         real_driving_start_date_time as real_driving_start, "
			+ "			case when a.real_driving_end_date_time > 0 then To_char( to_timestamp(a.real_driving_end_date_time/1000), "
			+ "			                          'YYYY-MM-DD HH24:MI:SS:MS') "
			+ "	             else '0' "
			+ "			end as real_driving_end_date_time, "
			+ "         real_driving_end_date_time as real_driving_end,  "
			+ "			a.route "
			+ "			FROM   s_army.carplan2 a "
			+ "			       INNER JOIN (SELECT Max(id) AS m_id, "
			+ "			                          car_license_no "
			+ "			                   FROM   s_army.carplan2 "
			+ "			                   WHERE  to_timestamp(real_driving_start_date_time/1000) < Now() "
			+ "							          and deleted_at is null "
			+ "			                          and car_license_no = :carLicenseNo "
			+ "			                   GROUP  BY car_license_no "
			+ "			                   ORDER  BY Max(id) DESC) c "
			+ "			               ON a.id = c.m_id "